title: Cyan's Page
description: Personal page of Cyan
# theme: leap-day
# theme: modernist
theme: time-machine

# Let Jekyll process Markdown everywhere
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - posts
